# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20150715_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='command_line_utilities',
            field=models.ManyToManyField(blank=True, to='utility.CommandLineUtility', verbose_name='kommandoradsverktyg'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='python_utilities',
            field=models.ManyToManyField(blank=True, to='utility.PythonUtility', verbose_name='pythonverktyg'),
        ),
    ]
